LOGISTIC REGRESSION

IMPORT LIBRARIES

In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [39]:
dataset = pd.read_csv(r"C:\Users\LOQ\Downloads\BREAST-CANCER-CLASSIFICATION\breast+cancer+wisconsin+diagnostic\wdbc.data")

In [40]:
dataset.head()

842302  M  17.99  10.38   122.8    1001   0.1184   0.2776  0.3001  \
0    842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869   
1  84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974   
2  84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414   
3  84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980   
4    843786  M  12.45  15.70   82.57   477.1  0.12780  0.17000  0.1578   

    0.1471  ...  25.38  17.33   184.6    2019  0.1622  0.6656  0.7119  0.2654  \
0  0.07017  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
1  0.12790  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
2  0.10520  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
3  0.10430  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   
4  0.08089  ...  15.47  23.75  103.40   741.6  0.1791  0.5249  0.5355  0.1741   

   0.4601   0.1189  
0  0.2750  0.08902  
1  0.3613  0.08758  
2  0.6638  0.17300  
3  0.2364  0.07678  
4  0.3985  0.12440  

[5 rows x 32 columns]

NO NAMES FOR COLUMN SO ASSIGN NAME

In [41]:
columns = [
    'id',
    'diagnosis',
    'radius_mean',
    'texture_mean',
    'perimeter_mean',
    'area_mean',
    'smoothness_mean',
    'compactness_mean',
    'concavity_mean',
    'concave_points_mean',
    'symmetry_mean',
    'fractal_dimension_mean',
    'radius_se',
    'texture_se',
    'perimeter_se',
    'area_se',
    'smoothness_se',
    'compactness_se',
    'concavity_se',
    'concave_points_se',
    'symmetry_se',
    'fractal_dimension_se',
    'radius_worst',
    'texture_worst',
    'perimeter_worst',
    'area_worst',
    'smoothness_worst',
    'compactness_worst',
    'concavity_worst',
    'concave_points_worst',
    'symmetry_worst',
    'fractal_dimension_worst'
]


In [42]:
dataset.columns = columns

In [43]:
dataset.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842517         M        20.57         17.77          132.90     1326.0   
1  84300903         M        19.69         21.25          130.00     1203.0   
2  84348301         M        11.42         20.38           77.58      386.1   
3  84358402         M        20.29         14.34          135.10     1297.0   
4    843786         M        12.45         15.70           82.57      477.1   

   smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
0          0.08474           0.07864          0.0869              0.07017   
1          0.10960           0.15990          0.1974              0.12790   
2          0.14250           0.28390          0.2414              0.10520   
3          0.10030           0.13280          0.1980              0.10430   
4          0.12780           0.17000          0.1578              0.08089   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         24.99          23.41           158.80      1956.0   
1  ...         23.57          25.53           152.50      1709.0   
2  ...         14.91          26.50            98.87       567.7   
3  ...         22.54          16.67           152.20      1575.0   
4  ...         15.47          23.75           103.40       741.6   

   smoothness_worst  compactness_worst  concavity_worst  concave_points_worst  \
0            0.1238             0.1866           0.2416                0.1860   
1            0.1444             0.4245           0.4504                0.2430   
2            0.2098             0.8663           0.6869                0.2575   
3            0.1374             0.2050           0.4000                0.1625   
4            0.1791             0.5249           0.5355                0.1741   

   symmetry_worst  fractal_dimension_worst  
0          0.2750                  0.08902  
1          0.3613                  0.08758  
2          0.6638                  0.17300  
3          0.2364                  0.07678  
4          0.3985                  0.12440  

[5 rows x 32 columns]

In [44]:
dataset.shape

(568, 32)

In [45]:
dataset.describe

<bound method NDFrame.describe of            id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842517         M        20.57         17.77          132.90     1326.0   
1    84300903         M        19.69         21.25          130.00     1203.0   
2    84348301         M        11.42         20.38           77.58      386.1   
3    84358402         M        20.29         14.34          135.10     1297.0   
4      843786         M        12.45         15.70           82.57      477.1   
..        ...       ...          ...           ...             ...        ...   
563    926424         M        21.56         22.39          142.00     1479.0   
564    926682         M        20.13         28.25          131.20     1261.0   
565    926954         M        16.60         28.08          108.30      858.1   
566    927241         M        20.60         29.33          140.10     1265.0   
567     92751         B         7.76         24.54           47.92      181

DATA VISUALIZATION AND PREPROCESSSING


CHANGE M AND B TO BINARY VALUES , CHNGE ID COLUMN TO INDEX OF DATAFRAME

In [46]:
dataset['diagnosis'] = dataset['diagnosis'].apply(lambda x: '1' if x== 'M' else '0')

In [47]:
print(dataset.columns)


Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave_points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave_points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')


In [48]:
dataset.columns[:5]


Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean'], dtype='object')

In [49]:
print(dataset.groupby('diagnosis').size())

diagnosis
0    357
1    211
dtype: int64


In [50]:
dataset.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842517         1        20.57         17.77          132.90     1326.0   
1  84300903         1        19.69         21.25          130.00     1203.0   
2  84348301         1        11.42         20.38           77.58      386.1   
3  84358402         1        20.29         14.34          135.10     1297.0   
4    843786         1        12.45         15.70           82.57      477.1   

   smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
0          0.08474           0.07864          0.0869              0.07017   
1          0.10960           0.15990          0.1974              0.12790   
2          0.14250           0.28390          0.2414              0.10520   
3          0.10030           0.13280          0.1980              0.10430   
4          0.12780           0.17000          0.1578              0.08089   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         24.99          23.41           158.80      1956.0   
1  ...         23.57          25.53           152.50      1709.0   
2  ...         14.91          26.50            98.87       567.7   
3  ...         22.54          16.67           152.20      1575.0   
4  ...         15.47          23.75           103.40       741.6   

   smoothness_worst  compactness_worst  concavity_worst  concave_points_worst  \
0            0.1238             0.1866           0.2416                0.1860   
1            0.1444             0.4245           0.4504                0.2430   
2            0.2098             0.8663           0.6869                0.2575   
3            0.1374             0.2050           0.4000                0.1625   
4            0.1791             0.5249           0.5355                0.1741   

   symmetry_worst  fractal_dimension_worst  
0          0.2750                  0.08902  
1          0.3613                  0.08758  
2          0.6638                  0.17300  
3          0.2364                  0.07678  
4          0.3985                  0.12440  

[5 rows x 32 columns]

In [51]:
X = dataset.drop(['id', 'diagnosis'], axis=1).values
y = dataset['diagnosis'].values


In [52]:
print(X)

[[2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 ... 2.575e-01 6.638e-01 1.730e-01]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [53]:
print(y)

['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '0' '0' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '0' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '0' '0' '0' '0' '0' '1' '1'
 '0' '1' '1' '0' '0' '0' '0' '1' '0' '1' '1' '0' '0' '0' '0' '1' '0' '1'
 '1' '0' '1' '0' '1' '1' '0' '0' '0' '1' '1' '0' '1' '1' '1' '0' '0' '0'
 '1' '0' '0' '1' '1' '0' '0' '0' '1' '1' '0' '0' '0' '0' '1' '0' '0' '1'
 '0' '0' '0' '0' '0' '0' '0' '0' '1' '1' '1' '0' '1' '1' '0' '0' '0' '1'
 '1' '0' '1' '0' '1' '1' '0' '1' '1' '0' '0' '1' '0' '0' '1' '0' '0' '0'
 '0' '1' '0' '0' '0' '0' '0' '0' '0' '0' '0' '1' '0' '0' '0' '0' '1' '1'
 '0' '1' '0' '0' '1' '1' '0' '0' '1' '1' '0' '0' '0' '0' '1' '0' '0' '1'
 '1' '1' '0' '1' '0' '1' '0' '0' '0' '1' '0' '0' '1' '1' '0' '1' '1' '1'
 '1' '0' '1' '1' '1' '0' '1' '0' '1' '0' '0' '1' '0' '1' '1' '1' '1' '0'
 '0' '1' '1' '0' '0' '0' '1' '0' '0' '0' '0' '0' '1' '1' '0' '0' '1' '0'
 '0' '1' '1' '0' '1' '0' '0' '0' '0' '1' '0' '0' '0

SPLIT DATASET

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train , y_test = train_test_split(X,y,test_size=0.25,random_state=21)

In [55]:
print(X)

[[2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 ... 2.575e-01 6.638e-01 1.730e-01]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [56]:
print(y)

['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '0' '0' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '0' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '0' '0' '0' '0' '0' '1' '1'
 '0' '1' '1' '0' '0' '0' '0' '1' '0' '1' '1' '0' '0' '0' '0' '1' '0' '1'
 '1' '0' '1' '0' '1' '1' '0' '0' '0' '1' '1' '0' '1' '1' '1' '0' '0' '0'
 '1' '0' '0' '1' '1' '0' '0' '0' '1' '1' '0' '0' '0' '0' '1' '0' '0' '1'
 '0' '0' '0' '0' '0' '0' '0' '0' '1' '1' '1' '0' '1' '1' '0' '0' '0' '1'
 '1' '0' '1' '0' '1' '1' '0' '1' '1' '0' '0' '1' '0' '0' '1' '0' '0' '0'
 '0' '1' '0' '0' '0' '0' '0' '0' '0' '0' '0' '1' '0' '0' '0' '0' '1' '1'
 '0' '1' '0' '0' '1' '1' '0' '0' '1' '1' '0' '0' '0' '0' '1' '0' '0' '1'
 '1' '1' '0' '1' '0' '1' '0' '0' '0' '1' '0' '0' '1' '1' '0' '1' '1' '1'
 '1' '0' '1' '1' '1' '0' '1' '0' '1' '0' '0' '1' '0' '1' '1' '1' '1' '0'
 '0' '1' '1' '0' '0' '0' '1' '0' '0' '0' '0' '0' '1' '1' '0' '0' '1' '0'
 '0' '1' '1' '0' '1' '0' '0' '0' '0' '1' '0' '0' '0

STANDARIZE

In [57]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [58]:
print(X)

[[2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 ... 2.575e-01 6.638e-01 1.730e-01]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [59]:
print(y)

['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '0' '0' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '0' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '0' '0' '0' '0' '0' '1' '1'
 '0' '1' '1' '0' '0' '0' '0' '1' '0' '1' '1' '0' '0' '0' '0' '1' '0' '1'
 '1' '0' '1' '0' '1' '1' '0' '0' '0' '1' '1' '0' '1' '1' '1' '0' '0' '0'
 '1' '0' '0' '1' '1' '0' '0' '0' '1' '1' '0' '0' '0' '0' '1' '0' '0' '1'
 '0' '0' '0' '0' '0' '0' '0' '0' '1' '1' '1' '0' '1' '1' '0' '0' '0' '1'
 '1' '0' '1' '0' '1' '1' '0' '1' '1' '0' '0' '1' '0' '0' '1' '0' '0' '0'
 '0' '1' '0' '0' '0' '0' '0' '0' '0' '0' '0' '1' '0' '0' '0' '0' '1' '1'
 '0' '1' '0' '0' '1' '1' '0' '0' '1' '1' '0' '0' '0' '0' '1' '0' '0' '1'
 '1' '1' '0' '1' '0' '1' '0' '0' '0' '1' '0' '0' '1' '1' '0' '1' '1' '1'
 '1' '0' '1' '1' '1' '0' '1' '0' '1' '0' '0' '1' '0' '1' '1' '1' '1' '0'
 '0' '1' '1' '0' '0' '0' '1' '0' '0' '0' '0' '0' '1' '1' '0' '0' '1' '0'
 '0' '1' '1' '0' '1' '0' '0' '0' '0' '1' '0' '0' '0

TRAIN DATASET

In [60]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

PREDICTION

In [61]:
print(classifier.predict(sc.transform([[17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871,
           1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193,
           25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189]])))


['1']


In [62]:
sample = [[17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871,
           1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193,
           25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189]]

scaled_sample = sc.transform(sample)
prediction = classifier.predict(scaled_sample)
print("Prediction:", prediction)


Prediction: ['1']


PREDCITION COMPARISON

In [63]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[['1' '1']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']

CONFUSION MATRIX

In [64]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)


[[86  0]
 [ 1 55]]


COMPUTE ACCURACY WITH K-FOLD CROSS VALIDATION

In [65]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9929577464788732

In [66]:
accuracy_score(y_test, y_pred, normalize=False)

141.0

KNN

In [67]:
from random import uniform
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,weights='uniform',metric="minkowski",p=2)
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [68]:
sample = [[17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871,
           1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193,
           25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189]]

scaled_sample = sc.transform(sample)
prediction = classifier.predict(scaled_sample)
print("Prediction:", prediction)


Prediction: ['1']


In [69]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[['1' '1']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']

In [70]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9647887323943662

In [71]:
accuracy_score(y_test, y_pred, normalize=False)

137.0

SVM

In [72]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear',random_state=0)
classifier.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [73]:
sample = [[17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871,
           1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193,
           25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189]]

scaled_sample = sc.transform(sample)
prediction = classifier.predict(scaled_sample)
print("Prediction:", prediction)


Prediction: ['1']


In [74]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[['1' '1']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']

In [75]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)


[[86  0]
 [ 2 54]]


In [76]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9859154929577465

In [77]:
accuracy_score(y_test, y_pred, normalize=False)

140.0

KERNEL SVM

In [78]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf',random_state=0)
classifier.fit(X_train,y_train)

SVC(random_state=0)

In [79]:
sample = [[17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871,
           1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193,
           25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189]]

scaled_sample = sc.transform(sample)
prediction = classifier.predict(scaled_sample)
print("Prediction:", prediction)


Prediction: ['1']


In [80]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[['1' '1']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']

In [81]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)


[[86  0]
 [ 2 54]]


In [82]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9859154929577465

In [83]:
accuracy_score(y_test, y_pred, normalize=False)

140.0

DECISION TREE

In [84]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [85]:
sample = [[17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871,
           1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193,
           25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189]]

scaled_sample = sc.transform(sample)
prediction = classifier.predict(scaled_sample)
print("Prediction:", prediction)


Prediction: ['1']


In [86]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[['1' '1']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']

In [87]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)


[[84  2]
 [ 3 53]]


In [88]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9647887323943662

In [89]:
accuracy_score(y_test, y_pred, normalize=False)

137.0

RANDOM FOREST

In [90]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,criterion='entropy',random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

In [91]:
sample = [[17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871,
           1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193,
           25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189]]

scaled_sample = sc.transform(sample)
prediction = classifier.predict(scaled_sample)
print("Prediction:", prediction)


Prediction: ['1']


In [92]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)


[[84  2]
 [ 3 53]]


In [93]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9647887323943662

In [94]:
accuracy_score(y_test, y_pred, normalize=False)

137.0

NAIVE BYES

In [95]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB()

In [96]:
sample = [[17.99, 10.38, 122.8, 1001, 0.1184, 0.2776, 0.3001, 0.1471, 0.2419, 0.07871,
           1.095, 0.9053, 8.589, 153.4, 0.006399, 0.04904, 0.05373, 0.01587, 0.03003, 0.006193,
           25.38, 17.33, 184.6, 2019, 0.1622, 0.6656, 0.7119, 0.2654, 0.4601, 0.1189]]

scaled_sample = sc.transform(sample)
prediction = classifier.predict(scaled_sample)
print("Prediction:", prediction)


Prediction: ['1']


In [97]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[['1' '1']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['0' '1']
 ['1' '1']
 ['1' '0']
 ['0' '0']
 ['0' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['0' '0']
 ['1' '1']
 ['1' '1']
 ['0' '0']
 ['0' '0']

In [98]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)


[[83  3]
 [ 7 49]]


In [99]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9295774647887324

In [100]:
accuracy_score(y_test, y_pred, normalize=False)

132.0